import type { AppData } from './types';

export const seed: AppData = {
  clusters: [
    { id: "deck",   title: "Über Deck",            order: 1 },
    { id: "below",  title: "Unter Deck",           order: 2 },
    { id: "engine", title: "Technik / Maschinen",  order: 3 },
    { id: "safety", title: "Sicherheit & Doku",    order: 4 }
  ],
  tasks: [
    // ÜBER DECK (20)
    { id:"deck-01", clusterId:"deck", title:"Rumpf/Deck: Sichtprüfung auf Schäden, Risse, Delamination", status:"open", order:1 },
    { id:"deck-02", clusterId:"deck", title:"Reling/Handläufe: fest, keine losen Stützen", status:"open", order:2 },
    { id:"deck-03", clusterId:"deck", title:"Klampen/Belegpunkte: fest, keine Haarrisse im Laminat", status:"open", order:3 },
    { id:"deck-04", clusterId:"deck", title:"Ankerwinde: läuft vor/zurück, Notstopp ok", status:"open", order:4 },
    { id:"deck-05", clusterId:"deck", title:"Anker + Kette/Leine: Zustand, Markierungen, Sicherung", status:"open", order:5 },
    { id:"deck-06", clusterId:"deck", title:"Bugkorb/Heckkorb: fest, keine verbogenen Elemente", status:"open", order:6 },
    { id:"deck-07", clusterId:"deck", title:"Luken/Decksluken: dicht, Verriegelung funktioniert", status:"open", order:7 },
    { id:"deck-08", clusterId:"deck", title:"Fenster/Schotten: Dichtungen ok, keine Leckspuren", status:"open", order:8 },
    { id:"deck-09", clusterId:"deck", title:"Winschen: leichtgängig, Sperrklinken hörbar, Kurbel passt", status:"open", order:9 },
    { id:"deck-10", clusterId:"deck", title:"Blöcke/Umlenkrollen: frei drehend, keine Risse", status:"open", order:10 },
    { id:"deck-11", clusterId:"deck", title:"Fallen/Schoten: Scheuerstellen, Knoten, Enden gesichert", status:"open", order:11 },
    { id:"deck-12", clusterId:"deck", title:"Steuerstand: Radpinne/Steuerrad frei, Anschlag ok", status:"open", order:12 },
    { id:"deck-13", clusterId:"deck", title:"Ruderanlage: Sichtprüfung, Spiel/Knacken beim Lenken", status:"open", order:13 },
    { id:"deck-14", clusterId:"deck", title:"Navigationlichter: alle Funktionen testen", status:"open", order:14 },
    { id:"deck-15", clusterId:"deck", title:"Deckdusche/Spüleinrichtung: dicht, Schlauch ok", status:"open", order:15 },
    { id:"deck-16", clusterId:"deck", title:"Bimini/Sprayhood: Zustand, Reißverschlüsse, Befestigung", status:"open", order:16 },
    { id:"deck-17", clusterId:"deck", title:"Badeplattform/Leiter: sicher, Verriegelung ok", status:"open", order:17 },
    { id:"deck-18", clusterId:"deck", title:"Fender/Leinen: ausreichende Menge + Zustand", status:"open", order:18 },
    { id:"deck-19", clusterId:"deck", title:"Rettungsinsel-Halterung: korrekt gesichert (falls vorhanden)", status:"open", order:19 },
    { id:"deck-20", clusterId:"deck", title:"Decksabläufe/Scuppers: frei, keine Verstopfung", status:"open", order:20 },

    // UNTER DECK (20)
    { id:"below-01", clusterId:"below", title:"Bilge: trocken/sauber, keine Öl- oder Dieselspuren", status:"open", order:1 },
    { id:"below-02", clusterId:"below", title:"Innenraum: Sichtprüfung auf Wasserspuren/Schimmel", status:"open", order:2 },
    { id:"below-03", clusterId:"below", title:"See-WC: spült, Ventile/Schläuche dicht, Geruch ok", status:"open", order:3 },
    { id:"below-04", clusterId:"below", title:"Fäkalientank: Füllstandsanzeige + Ventilstellung geprüft", status:"open", order:4 },
    { id:"below-05", clusterId:"below", title:"Frischwasser: Tankstand, Pumpe läuft, Druck hält", status:"open", order:5 },
    { id:"below-06", clusterId:"below", title:"Wasserhähne: dicht, warm/kalt (falls vorhanden)", status:"open", order:6 },
    { id:"below-07", clusterId:"below", title:"Gasherd: Zündung, Flammenbild, Absperrhahn erreichbar", status:"open", order:7 },
    { id:"below-08", clusterId:"below", title:"Gasflaschenfach: Entlüftung frei, Schlauch/Regler ok", status:"open", order:8 },
    { id:"below-09", clusterId:"below", title:"Kühlschrank: kühlt, Dichtung ok, Ablauf frei", status:"open", order:9 },
    { id:"below-10", clusterId:"below", title:"Heizung: startet, Gebläse läuft, keine Fehlermeldung", status:"open", order:10 },
    { id:"below-11", clusterId:"below", title:"Navigation/Instrumente innen: Displays, Beleuchtung", status:"open", order:11 },
    { id:"below-12", clusterId:"below", title:"Autopilot/Steuercomputer: Selbsttest/Grundfunktion", status:"open", order:12 },
    { id:"below-13", clusterId:"below", title:"Sicherungen/Schalttafel: beschriftet, Ersatzsicherungen da", status:"open", order:13 },
    { id:"below-14", clusterId:"below", title:"230V Landstrom: FI/LS testen, Steckdosen stichprobenartig", status:"open", order:14 },
    { id:"below-15", clusterId:"below", title:"Batteriemonitor: Werte plausibel, Verbraucher identifiziert", status:"open", order:15 },
    { id:"below-16", clusterId:"below", title:"Luken/Fenster innen: Verriegelung, Verdunkelung, Insektenschutz", status:"open", order:16 },
    { id:"below-17", clusterId:"below", title:"Polster/Inventar: Vollständigkeit nach Übergabeliste", status:"open", order:17 },
    { id:"below-18", clusterId:"below", title:"Werkzeug/Spare Parts: Grundset vorhanden (Impeller, Filter etc.)", status:"open", order:18 },
    { id:"below-19", clusterId:"below", title:"Feuchtigkeit: Entfeuchter/Belüftung, keine Kondensnester", status:"open", order:19 },
    { id:"below-20", clusterId:"below", title:"Dokumentation an Bord: Handbücher/Schaltpläne auffindbar", status:"open", order:20 },

    // TECHNIK / MASCHINEN (20)
    { id:"engine-01", clusterId:"engine", title:"Seeventile gangbar und dicht", status:"open", order:1 },
    { id:"engine-02", clusterId:"engine", title:"Seeventile beschriftet (offen/geschlossen erkennbar)", status:"open", order:2 },
    { id:"engine-03", clusterId:"engine", title:"Motorölstand geprüft", status:"open", order:3 },
    { id:"engine-04", clusterId:"engine", title:"Motoröl optisch sauber (keine Emulsion)", status:"open", order:4 },
    { id:"engine-05", clusterId:"engine", title:"Getriebeölstand geprüft", status:"open", order:5 },
    { id:"engine-06", clusterId:"engine", title:"Kühlwasserstand geprüft (geschlossener Kreislauf)", status:"open", order:6 },
    { id:"engine-07", clusterId:"engine", title:"Seewasserfilter sauber und korrekt montiert", status:"open", order:7 },
    { id:"engine-08", clusterId:"engine", title:"Impeller-Status dokumentiert (Wechselintervall bekannt)", status:"open", order:8 },
    { id:"engine-09", clusterId:"engine", title:"Keilriemen Spannung und Zustand geprüft", status:"open", order:9 },
    { id:"engine-10", clusterId:"engine", title:"Ersatz-Keilriemen an Bord", status:"open", order:10 },
    { id:"engine-11", clusterId:"engine", title:"Kraftstofffilter sauber / Wechselintervall bekannt", status:"open", order:11 },
    { id:"engine-12", clusterId:"engine", title:"Ersatz-Dieselfilter an Bord", status:"open", order:12 },
    { id:"engine-13", clusterId:"engine", title:"Kraftstoffleitungen dicht (keine Undichtigkeiten)", status:"open", order:13 },
    { id:"engine-14", clusterId:"engine", title:"Batteriehauptschalter funktionstüchtig", status:"open", order:14 },
    { id:"engine-15", clusterId:"engine", title:"Batteriespannung gemessen", status:"open", order:15 },
    { id:"engine-16", clusterId:"engine", title:"Ladegerät / Lichtmaschine lädt korrekt", status:"open", order:16 },
    { id:"engine-17", clusterId:"engine", title:"Bilgepumpe automatisch & manuell getestet", status:"open", order:17 },
    { id:"engine-18", clusterId:"engine", title:"Hochwasser-Alarm funktioniert", status:"open", order:18 },
    { id:"engine-19", clusterId:"engine", title:"Wellenanlage / Saildrive optisch geprüft", status:"open", order:19 },
    { id:"engine-20", clusterId:"engine", title:"Kühlwasseraustritt am Auspuff bei Motorlauf sichtbar", status:"open", order:20 },

    // SICHERHEIT & DOKU (20)
    { id:"safety-01", clusterId:"safety", title:"Feuerlöscher: Anzahl, Plomben, Prüfdatum", status:"open", order:1 },
    { id:"safety-02", clusterId:"safety", title:"Feuerlöschdecke: vorhanden & zugänglich", status:"open", order:2 },
    { id:"safety-03", clusterId:"safety", title:"Rettungswesten: Größe/Anzahl passend, CO2-Patrone ok", status:"open", order:3 },
    { id:"safety-04", clusterId:"safety", title:"Lifebelts/Sicherheitsleinen: vorhanden, Nähte/Schäkel ok", status:"open", order:4 },
    { id:"safety-05", clusterId:"safety", title:"Lifelines/Jacklines: vorhanden oder Plan festgelegt", status:"open", order:5 },
    { id:"safety-06", clusterId:"safety", title:"EPIRB/PLB: vorhanden, Registrierung/Checkdatum", status:"open", order:6 },
    { id:"safety-07", clusterId:"safety", title:"AIS/UKW: Send/Empfang, MMSI korrekt, DSC Test (falls möglich)", status:"open", order:7 },
    { id:"safety-08", clusterId:"safety", title:"Signalraketen/Handfackeln: Haltbarkeit geprüft", status:"open", order:8 },
    { id:"safety-09", clusterId:"safety", title:"Rettungsring/Licht: vorhanden, Leine ok", status:"open", order:9 },
    { id:"safety-10", clusterId:"safety", title:"Notpinne: vorhanden, Einbau/Bedienung klar", status:"open", order:10 },
    { id:"safety-11", clusterId:"safety", title:"Erste-Hilfe-Set: vollständig, Haltbarkeiten ok", status:"open", order:11 },
    { id:"safety-12", clusterId:"safety", title:"Werkzeug für Leck/Notfall: Holzdübel/Stopfen an Seeventilen", status:"open", order:12 },
    { id:"safety-13", clusterId:"safety", title:"Lenzmittel: Eimer/Handlenzpumpe (falls vorhanden) geprüft", status:"open", order:13 },
    { id:"safety-14", clusterId:"safety", title:"Anker-Notfallplan: Zweitanker/Notanker vorhanden (falls vorgesehen)", status:"open", order:14 },
    { id:"safety-15", clusterId:"safety", title:"Rettungsinsel: Service-Datum & Auslösemechanismus check", status:"open", order:15 },
    { id:"safety-16", clusterId:"safety", title:"Dokumente: Registrierung/Flagge/Versicherungspapiere an Bord", status:"open", order:16 },
    { id:"safety-17", clusterId:"safety", title:"Funkzeugnisse/Skipper-Lizenzen: Kopien verfügbar (wenn nötig)", status:"open", order:17 },
    { id:"safety-18", clusterId:"safety", title:"Charter/Übergabe-Protokoll: vorhandene Schäden dokumentiert (Fotos)", status:"open", order:18 },
    { id:"safety-19", clusterId:"safety", title:"Notrufnummern/Landkontakt: Liste gespeichert & ausgedruckt", status:"open", order:19 },
    { id:"safety-20", clusterId:"safety", title:"Check: Alle Notausgänge/Fluchtwege frei & bekannt", status:"open", order:20 }
  ]
};
